#!/usr/bin/env python3
import pathlib
import sys


def parse_table(path):
    entries = []
    for raw in pathlib.Path(path).read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 3:
            raise SystemExit(f"bad syscall table line: {raw}")
        entries.append((int(parts[0]), parts[1], parts[2]))
    return entries


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_linux_syscalls.py <linux_syscall.tbl> <out.c>")
    entries = parse_table(sys.argv[1])
    max_nr = max(nr for nr, _, _ in entries)
    by_nr = {nr: (name, target) for nr, name, target in entries}

    out = [
        "/* Generated by tools/gen_linux_syscalls.py. Do not edit by hand. */",
        '#include "linux_syscall_table.h"',
        "",
        f"const uint64_t linux_syscall_table_size = {max_nr + 1};",
        "",
        "const struct linux_syscall_desc linux_syscall_table[] = {",
    ]
    for nr in range(max_nr + 1):
        if nr in by_nr:
            name, target = by_nr[nr]
            out.append(f'    [{nr}] = {{ "{name}", "{target}" }},')
        else:
            out.append(f'    [{nr}] = {{ 0, 0 }},')
    out.append("};")
    out.append("")
    pathlib.Path(sys.argv[2]).write_text("\n".join(out), encoding="utf-8")


if __name__ == "__main__":
    main()
